#!/usr/bin/env python

import argparse
import os

from bart.api import BartApi

API_KEY = os.environ.get('API_KEY', None)


def main():
    print 'test'


def advisory_fn(c, args):
    if args.cmd == 'bsa':
        out = c.get_current_advisory(orig=args.station)
        print('{station} - {description}'.format(**out['bsa']))
    elif args.cmd == 'count':
        print(c.get_number_of_trains()['traincount'])
    elif args.cmd == 'elev':
        print(c.get_elevator_status()['bsa']['description'])


def stn_fn(c, args):
    if args.cmd == 'list':
        for station in c.get_stations()['stations']['station']:
            print('{abbr} - {name}'.format(**station))


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description='BART CLI')
    parser.add_argument('--version', action='version',
                        version='2.0', help='Current version of the BART API')
    parser.add_argument('-k', '--key', required=not API_KEY,
                        help='BART API Key')

    # Set up subparsers
    subparsers = parser.add_subparsers(title='subcommands',
                                       description='valid subcommands')

    # ## Advisories
    bsa = subparsers.add_parser('advisory', help="Advisories")
    bsa.set_defaults(func=advisory_fn)

    # BSA Subparser
    bsa_sub = bsa.add_subparsers(title='bsa',
                                 description="Get current advisory")

    # Current Advisories
    advisory = bsa_sub.add_parser('bsa', help="Current Advisory")
    advisory.set_defaults(cmd='bsa')
    advisory.add_argument('--station', default='all',
                          help="Station Abbreviation")

    # Train Count
    count = bsa_sub.add_parser('count', help="Train Count")
    count.set_defaults(cmd='count')

    # Elevator
    count = bsa_sub.add_parser('elev', help="Elevator Status")
    count.set_defaults(cmd='elev')

    # ## Real-Time Estimates
    etd = subparsers.add_parser('etd', help="Real-Time Estimates")

    # ## Route Information
    route = subparsers.add_parser('route', help="Route Information")

    # ## Schedule Information
    sched = subparsers.add_parser('sched', help="Schedule Information")

    # ## Station Information
    stn = subparsers.add_parser('station', help="Station Information")
    stn.set_defaults(func=stn_fn)

    # Station Subparser
    stn_sub = stn.add_subparsers(title='stn',
                                 description="Stations")
    list = stn_sub.add_parser('list', help="Station List")
    list.set_defaults(cmd='list')

    args = parser.parse_args()

    if API_KEY is None:
        API_KEY = args.key

    c = BartApi(API_KEY)

    args.func(c, args)
